version: "3.7"

services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=users
    
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8000:8080

  flask:
    build: ./app
    container_name: flask
    restart: unless-stopped
    ports:
      - 5000:5000